
import { GoogleGenAI, Modality } from "@google/genai";
import { CustomizationOptions } from '../types';

const MODEL_NAME = "gemini-2.5-flash-image";

function fileToGenerativePart(base64Data: string, mimeType: string) {
  return {
    inlineData: {
      data: base64Data,
      mimeType
    },
  };
}

const buildPrompt = (options: CustomizationOptions): string => {
  return `Generate a photo-realistic, tailored clothing swap onto the provided user photo. The goal is to perfectly render a high-end, custom-stitched Gents Saya-Kurta from Fatemi Tailors.
SPECIFICATIONS:
Garment: Saya-Kurta, ${options.fit} cut, using a ${options.fabric} texture.
Color: Exact color is a uniform ${options.color} (white or pastel only).
Reference Image Match: The collar, placket, and cuff design MUST precisely match the reference image available at this URL: ${options.collar.imageUrl}. Apply the design with a tailored finish.
Integration: Maintain the user's pose, lighting, background, and shadows from the original photo. The new garment must be seamlessly integrated and look like it was worn when the photo was taken. The result must be photorealistic.
CRITICAL: Do not alter the user's face, hair, or body structure. The output must be only the final image.`;
};


export const generateTryOnImage = async (
  userImageBase64: string,
  userImageMimeType: string,
  options: CustomizationOptions
): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY is not set in environment variables.");
    }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const textPrompt = buildPrompt(options);
  const imagePart = fileToGenerativePart(userImageBase64, userImageMimeType);

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
        parts: [
            imagePart,
            { text: textPrompt },
        ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
};
